# Generated by Django 2.2 on 2019-11-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20191103_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
