# Generated by Django 2.2 on 2019-11-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_item_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='inventory',
            field=models.IntegerField(default=1),
        ),
    ]
